In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving superstore_final_dataset (1).csv to superstore_final_dataset (1).csv

In [ ]:
df= pd.read_csv("superstore_final_dataset (1).csv", encoding="latin1")

In [ ]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

In [ ]:
df.shape

(9800, 18)

In [ ]:
df.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State',
       'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub_Category',
       'Product_Name', 'Sales'],
      dtype='object')

In [ ]:
df.info

<bound method DataFrame.info of       Row_ID        Order_ID  Order_Date   Ship_Date       Ship_Mode  \
0          1  CA-2017-152156   8/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156   8/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688   12/6/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608   12/1/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608   12/1/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608   12/1/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608   12/1/2016  17/01/2016  Standard Class

     Customer_ID     Customer_Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335     Sean O Donnel   Consumer  United States  Fort Lauderdale
4       SO-20335     Sean O Donnel   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal_Code   Region       Product_ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub_Category                                       Product_Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775
4         Storage                      Eldon Fold N Roll Cart System   22.3680
...           ...                                                ...       ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797       Phones                                        GE 30524EE4  235.1880
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 18 columns]>

# **how many missing values are present in each column**

In [ ]:
df.isnull().sum()

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

# **checks whether a complete row is repeated**

In [ ]:
df.duplicated().sum()

np.int64(0)

# **helped us understand the numerical columns**

In [ ]:
df.describe()

            Row_ID   Postal_Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

# **spot differences in spelling/capitalization**

In [ ]:
df["Category"].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

# cleaning if there is actually a problem

In [ ]:
df["Category"]=df["Category"].str.strip().str.title()

In [ ]:
df["Region"].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [ ]:
df["Segment"].unique()

array(['Consumer', 'Corporate', 'Home Office'], dtype=object)

In [ ]:
df["Sub_Category"].unique()

array(['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage',
       'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper',
       'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines',
       'Copiers'], dtype=object)

In [ ]:
df["Ship_Mode"].unique()

array(['Second Class', 'Standard Class', 'First Class', 'Same Day'],
      dtype=object)

# **make sure both dates are actually stored as dates**

In [ ]:
df[["Order_Date","Ship_Date"]].dtypes

Order_Date    datetime64[ns]
Ship_Date     datetime64[ns]
dtype: object

# **currently treating these columns as text, not actual dates.**

In [ ]:
df["Order_Date"]= pd.to_datetime(df["Order_Date"],dayfirst=True)

In [ ]:
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"], dayfirst=True)

# **doesn't contain negative zero**

In [ ]:
(df["Sales"]<=0).sum()

np.int64(0)

## **order can contain multiple products**

In [ ]:
df["Order_ID"].nunique()

4922

In [ ]:
df["Customer_ID"].nunique()

793

In [ ]:
df["Product_ID"].nunique()

1861

In [ ]:
df["State"].nunique()

49

In [ ]:
len(df)

9800

# **check whether one Product_ID is linked to multiple Product_Names**

In [ ]:
df.groupby("Product_ID")["Product_Name"].nunique().max()

2

In [ ]:
product_check= df.groupby("Product_ID")["Product_Name"].nunique()

In [ ]:
product_check[product_check>1]

Product_ID
FUR-BO-10002213    2
FUR-CH-10001146    2
FUR-FU-10001473    2
FUR-FU-10004017    2
FUR-FU-10004091    2
FUR-FU-10004270    2
FUR-FU-10004848    2
FUR-FU-10004864    2
OFF-AP-10000576    2
OFF-AR-10001149    2
OFF-BI-10002026    2
OFF-BI-10004632    2
OFF-BI-10004654    2
OFF-PA-10000357    2
OFF-PA-10000477    2
OFF-PA-10000659    2
OFF-PA-10001166    2
OFF-PA-10001950    2
OFF-PA-10001970    2
OFF-PA-10002195    2
OFF-PA-10002377    2
OFF-PA-10003022    2
OFF-ST-10001228    2
OFF-ST-10004950    2
TEC-AC-10002049    2
TEC-AC-10002550    2
TEC-AC-10003832    2
TEC-MA-10001148    2
TEC-PH-10001530    2
TEC-PH-10001795    2
TEC-PH-10002200    2
TEC-PH-10002310    2
TEC-PH-10004531    2
Name: Product_Name, dtype: int64

In [ ]:
df.groupby("Product_ID")["Product_Name"].nunique().value_counts()

Product_Name
1    1828
2      33
Name: count, dtype: int64

# **need to know what time period our data covers**

In [ ]:
df["Order_Date"].min(), df["Order_Date"].max()

(Timestamp('2015-01-03 00:00:00'), Timestamp('2018-12-30 00:00:00'))

In [ ]:
df.columns.tolist()

['Row_ID',
 'Order_ID',
 'Order_Date',
 'Ship_Date',
 'Ship_Mode',
 'Customer_ID',
 'Customer_Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal_Code',
 'Region',
 'Product_ID',
 'Category',
 'Sub_Category',
 'Product_Name',
 'Sales']

# **Total Revenue = Sum of Sales**

In [ ]:
Total_sales=df["Sales"].sum()

In [ ]:
Total_sales

np.float64(2261536.7827000003)

In [ ]:
Total_orders=  df["Order_ID"].nunique()

In [ ]:
Total_orders

4922

# **AOV = Total Revenue ÷ Number of Orders**

In [ ]:
Avg= Total_sales/Total_orders

In [ ]:
Avg

np.float64(459.4751691791955)

# **load clean data**

In [ ]:
df.to_excel("Superstore_Cleaned.xlsx", index= False)

In [ ]:
from google.colab import files

In [ ]:
files.download("Superstore_Cleaned.xlsx")